import React from 'react';
import { BookOpen, Key, Cpu, Copy, Check } from 'lucide-react';
import { OnboardingDoc } from '../services/api';

interface DocViewerProps {
  doc: OnboardingDoc | null;
}

export default function DocViewer({ doc }: DocViewerProps) {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!doc) {
    return (
      <div className="p-6 text-center text-slate-400 glass-panel rounded-xl h-full flex flex-col items-center justify-center">
        <BookOpen className="w-12 h-12 text-slate-600 mb-2" />
        <p>No documentation generated yet.</p>
        <p className="text-xs text-slate-500">Ingest a codebase to read auto-generated setup, routing, and structures.</p>
      </div>
    );
  }

  return (
    <div className="glass-panel rounded-xl p-6 h-full overflow-y-auto custom-scrollbar border border-border bg-zinc-950/20 space-y-6">
      <div className="border-b border-border pb-4">
        <h2 className="text-xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-amber-200">
          {doc.title}
        </h2>
        <p className="text-[10px] text-zinc-400 mt-1 uppercase tracking-wider font-semibold">Generated by DevRamp AST Parser & Analyzer</p>
      </div>

      {/* Architecture Overview */}
      <section className="space-y-2">
        <h3 className="text-xs font-bold text-accent uppercase tracking-wider flex items-center gap-1.5">
          <Cpu className="w-3.5 h-3.5" /> Architecture Overview
        </h3>
        <p className="text-xs text-zinc-300 leading-relaxed bg-zinc-900/60 p-3.5 rounded-lg border border-border">
          {doc.architecture}
        </p>
      </section>

      {/* Modules Summary */}
      <section className="space-y-3">
        <h3 className="text-xs font-bold text-accent uppercase tracking-wider flex items-center gap-1.5">
          <BookOpen className="w-3.5 h-3.5" /> Component Map ({doc.modules.length} Entities)
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {doc.modules.map((mod, idx) => (
            <div key={idx} className="glass-card p-3 rounded-lg border border-border bg-zinc-900/40 space-y-1">
              <div className="flex justify-between items-start">
                <span className="font-bold text-xs text-white truncate max-w-[70%]">{mod.name}</span>
                <span className="text-[9px] uppercase tracking-wider px-2 py-0.5 rounded bg-zinc-950 border border-zinc-800 text-zinc-400">
                  {mod.type}
                </span>
              </div>
              <p className="text-[9px] text-zinc-500 font-mono truncate">{mod.file}</p>
              <p className="text-xs text-zinc-300 line-clamp-2">{mod.docstring}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Setup Instructions */}
      <section className="space-y-2">
        <div className="flex justify-between items-center">
          <h3 className="text-xs font-bold text-accent uppercase tracking-wider flex items-center gap-1.5">
            <Key className="w-3.5 h-3.5" /> Setup & Dependencies
          </h3>
          <button
            onClick={() => handleCopy(doc.setup)}
            className="text-[10px] bg-zinc-900 hover:bg-zinc-800 border border-border px-3 py-1.5 rounded-lg font-bold flex items-center gap-1 transition"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
            Copy Setup
          </button>
        </div>
        <div className="bg-zinc-950 border border-border rounded-lg p-4 font-mono text-xs text-zinc-300 overflow-x-auto whitespace-pre-wrap">
          {doc.setup}
        </div>
      </section>
    </div>
  );
}
